// <auto-generated />
using System;
using MartialArtsClubManagement.API.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MartialArtsClubManagement.API.Migrations
{
    [DbContext(typeof(QuanLyCLBVoThuatContext))]
    [Migration("20260529102812_AddNotificationRecipientFields")]
    partial class AddNotificationRecipientFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.CapDai", b =>
                {
                    b.Property<int>("MaCapDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCapDai"));

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenCapDai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThoiGianToiThieuThang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaCapDai")
                        .HasName("PK__CapDai__ABF5572A03D91FAD");

                    b.HasIndex(new[] { "ThuTu" }, "UQ__CapDai__2E2833D103247378")
                        .IsUnique();

                    b.ToTable("CapDai", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DangKyKem", b =>
                {
                    b.Property<int>("MaDangKyKem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKyKem"));

                    b.Property<int>("MaGoi")
                        .HasColumnType("int");

                    b.Property<int?>("MaHlv")
                        .HasColumnType("int")
                        .HasColumnName("MaHLV");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThaiPhanCong")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("ChoPhanCong");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("ChuaThanhToan");

                    b.HasKey("MaDangKyKem")
                        .HasName("PK__DangKyKe__113944DB23FBCD52");

                    b.HasIndex("MaGoi");

                    b.HasIndex("MaHlv");

                    b.HasIndex(new[] { "MaHocVien", "MaGoi" }, "UQ_DangKyKem")
                        .IsUnique();

                    b.ToTable("DangKyKem", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DangKyLop", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("ChuaThanhToan");

                    b.HasKey("MaDangKy")
                        .HasName("PK__DangKyLo__BA90F02DA76F7639");

                    b.HasIndex("MaLop");

                    b.HasIndex(new[] { "MaHocVien", "MaLop" }, "UQ_DangKyLop")
                        .IsUnique();

                    b.ToTable("DangKyLop", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DangKySuKien", b =>
                {
                    b.Property<int>("MaDangKySuKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKySuKien"));

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaThongBao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaDangKySuKien")
                        .HasName("PK__DangKySu__2308849504373920");

                    b.HasIndex("MaHocVien");

                    b.HasIndex(new[] { "MaThongBao", "MaHocVien" }, "UQ_DangKySuKien")
                        .IsUnique();

                    b.ToTable("DangKySuKien", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DiemDanh", b =>
                {
                    b.Property<int>("MaDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiemDanh"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayHoc")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CóMặt");

                    b.HasKey("MaDiemDanh")
                        .HasName("PK__DiemDanh__1512439D092DD1C7");

                    b.HasIndex(new[] { "MaDangKy", "NgayHoc" }, "UQ_DiemDanh")
                        .IsUnique();

                    b.ToTable("DiemDanh", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.GoiKemRieng", b =>
                {
                    b.Property<int>("MaGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoi"));

                    b.Property<bool>("DangSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoBuoi")
                        .HasColumnType("int");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaGoi")
                        .HasName("PK__GoiKemRi__3CD30F69BC1493F8");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("GoiKemRieng", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<int?>("MaCapDaiHienTai")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayGiaNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaHocVien")
                        .HasName("PK__HocVien__685B0E6A7E5D40CD");

                    b.HasIndex("MaCapDaiHienTai");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "UQ__HocVien__AD7C6528BDD8D950")
                        .IsUnique();

                    b.ToTable("HocVien", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.HuanLuyenVien", b =>
                {
                    b.Property<int>("MaHlv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHLV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHlv"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DangHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayVaoClb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("NgayVaoCLB")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaHlv")
                        .HasName("PK__HuanLuye__3C9029D84A99DD0D");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "UQ__HuanLuye__AD7C6528A0648C92")
                        .IsUnique();

                    b.ToTable("HuanLuyenVien", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.KetQuaThi", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<bool>("DaDat")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiemSo")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int?>("MaCapDaiMoi")
                        .HasColumnType("int");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKyThi")
                        .HasColumnType("int");

                    b.HasKey("MaKetQua")
                        .HasName("PK__KetQuaTh__D5B3102A0631BB40");

                    b.HasIndex("MaCapDaiMoi");

                    b.HasIndex("MaHocVien");

                    b.HasIndex(new[] { "MaKyThi", "MaHocVien" }, "UQ_KetQuaThi")
                        .IsUnique();

                    b.ToTable("KetQuaThi", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKhaiGiang")
                        .HasColumnType("date");

                    b.Property<int>("SoLuongToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ChuaMo");

                    b.HasKey("MaKhoaHoc")
                        .HasName("PK__KhoaHoc__48F0FF983557B136");

                    b.ToTable("KhoaHoc", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.KyThiThangDai", b =>
                {
                    b.Property<int>("MaKyThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyThi"));

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("NgayThi")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("SapDienRa");

                    b.HasKey("MaKyThi")
                        .HasName("PK__KyThiTha__1403DE9874F6BA18");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("KyThiThangDai", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LichHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaCapDai")
                        .HasColumnType("int");

                    b.Property<int>("MaHlv")
                        .HasColumnType("int")
                        .HasColumnName("MaHLV");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("PhongTap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop")
                        .HasName("PK__LopHoc__3B98D2731D2B6812");

                    b.HasIndex("MaCapDai");

                    b.HasIndex("MaHlv");

                    b.HasIndex(new[] { "MaKhoaHoc", "MaCapDai" }, "UQ_LopHoc_KhoaCapDai")
                        .IsUnique();

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<bool>("DangHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C652998BD228F");

                    b.HasIndex(new[] { "Email" }, "UQ__TaiKhoan__A9D105346080821C")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("ThongBao");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoanTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao")
                        .HasName("PK__ThongBao__04DEB54ECFA13B52");

                    b.HasIndex("MaTaiKhoanTao");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.VDangKyKemChoPhanCong", b =>
                {
                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<int>("MaDangKyKem")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime");

                    b.Property<int>("SoBuoi")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenHocVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("V_DangKyKemChoPhanCong", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.VHocVienDuDieuKienThi", b =>
                {
                    b.Property<string>("CapDaiHienTai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int?>("SoThangHienTai")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianToiThieuThang")
                        .HasColumnType("int");

                    b.Property<int>("ThuTuDaiHienTai")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("V_HocVienDuDieuKienThi", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.VHocVienVaCapDai", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<string>("MauSac")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("NgayGiaNhap")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenCapDai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ThuTuDai")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("V_HocVienVaCapDai", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.VLopHocChiTiet", b =>
                {
                    b.Property<string>("LichHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("PhongTap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenCapDai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHlv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenHLV");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.ToTable((string)null);

                    b.ToView("V_LopHocChiTiet", (string)null);
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DangKyKem", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.GoiKemRieng", "MaGoiNavigation")
                        .WithMany("DangKyKems")
                        .HasForeignKey("MaGoi")
                        .IsRequired()
                        .HasConstraintName("FK__DangKyKem__MaGoi__72C60C4A");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.HuanLuyenVien", "MaHlvNavigation")
                        .WithMany("DangKyKems")
                        .HasForeignKey("MaHlv")
                        .HasConstraintName("FK__DangKyKem__MaHLV__73BA3083");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.HocVien", "MaHocVienNavigation")
                        .WithMany("DangKyKems")
                        .HasForeignKey("MaHocVien")
                        .IsRequired()
                        .HasConstraintName("FK__DangKyKem__MaHoc__71D1E811");

                    b.Navigation("MaGoiNavigation");

                    b.Navigation("MaHlvNavigation");

                    b.Navigation("MaHocVienNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DangKyLop", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.HocVien", "MaHocVienNavigation")
                        .WithMany("DangKyLops")
                        .HasForeignKey("MaHocVien")
                        .IsRequired()
                        .HasConstraintName("FK__DangKyLop__MaHoc__5DCAEF64");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.LopHoc", "MaLopNavigation")
                        .WithMany("DangKyLops")
                        .HasForeignKey("MaLop")
                        .IsRequired()
                        .HasConstraintName("FK__DangKyLop__MaLop__5EBF139D");

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DangKySuKien", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.HocVien", "MaHocVienNavigation")
                        .WithMany("DangKySuKiens")
                        .HasForeignKey("MaHocVien")
                        .IsRequired()
                        .HasConstraintName("FK__DangKySuK__MaHoc__0B91BA14");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.ThongBao", "MaThongBaoNavigation")
                        .WithMany("DangKySuKiens")
                        .HasForeignKey("MaThongBao")
                        .IsRequired()
                        .HasConstraintName("FK__DangKySuK__MaTho__0A9D95DB");

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaThongBaoNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DiemDanh", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.DangKyLop", "MaDangKyNavigation")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("MaDangKy")
                        .IsRequired()
                        .HasConstraintName("FK__DiemDanh__MaDang__6477ECF3");

                    b.Navigation("MaDangKyNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.GoiKemRieng", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("GoiKemRiengs")
                        .HasForeignKey("MaKhoaHoc")
                        .IsRequired()
                        .HasConstraintName("FK__GoiKemRie__MaKho__693CA210");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.HocVien", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.CapDai", "MaCapDaiHienTaiNavigation")
                        .WithMany("HocViens")
                        .HasForeignKey("MaCapDaiHienTai")
                        .HasConstraintName("FK_HocVien_CapDai");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithOne("HocVien")
                        .HasForeignKey("MartialArtsClubManagement.API.Models.Entities.HocVien", "MaTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK__HocVien__MaTaiKh__49C3F6B7");

                    b.Navigation("MaCapDaiHienTaiNavigation");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.HuanLuyenVien", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithOne("HuanLuyenVien")
                        .HasForeignKey("MartialArtsClubManagement.API.Models.Entities.HuanLuyenVien", "MaTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK__HuanLuyen__MaTai__403A8C7D");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.KetQuaThi", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.CapDai", "MaCapDaiMoiNavigation")
                        .WithMany("KetQuaThis")
                        .HasForeignKey("MaCapDaiMoi")
                        .HasConstraintName("FK__KetQuaThi__MaCap__00200768");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.HocVien", "MaHocVienNavigation")
                        .WithMany("KetQuaThis")
                        .HasForeignKey("MaHocVien")
                        .IsRequired()
                        .HasConstraintName("FK__KetQuaThi__MaHoc__7F2BE32F");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.KyThiThangDai", "MaKyThiNavigation")
                        .WithMany("KetQuaThis")
                        .HasForeignKey("MaKyThi")
                        .IsRequired()
                        .HasConstraintName("FK__KetQuaThi__MaKyT__7E37BEF6");

                    b.Navigation("MaCapDaiMoiNavigation");

                    b.Navigation("MaHocVienNavigation");

                    b.Navigation("MaKyThiNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.KyThiThangDai", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("KyThiThangDais")
                        .HasForeignKey("MaKhoaHoc")
                        .IsRequired()
                        .HasConstraintName("FK__KyThiThan__MaKho__787EE5A0");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.LopHoc", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.CapDai", "MaCapDaiNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaCapDai")
                        .IsRequired()
                        .HasConstraintName("FK__LopHoc__MaCapDai__5629CD9C");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.HuanLuyenVien", "MaHlvNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaHlv")
                        .IsRequired()
                        .HasConstraintName("FK__LopHoc__MaHLV__571DF1D5");

                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.KhoaHoc", "MaKhoaHocNavigation")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .IsRequired()
                        .HasConstraintName("FK__LopHoc__MaKhoaHo__5535A963");

                    b.Navigation("MaCapDaiNavigation");

                    b.Navigation("MaHlvNavigation");

                    b.Navigation("MaKhoaHocNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.ThongBao", b =>
                {
                    b.HasOne("MartialArtsClubManagement.API.Models.Entities.TaiKhoan", "MaTaiKhoanTaoNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaTaiKhoanTao")
                        .IsRequired()
                        .HasConstraintName("FK__ThongBao__MaTaiK__05D8E0BE");

                    b.Navigation("MaTaiKhoanTaoNavigation");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.CapDai", b =>
                {
                    b.Navigation("HocViens");

                    b.Navigation("KetQuaThis");

                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.DangKyLop", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.GoiKemRieng", b =>
                {
                    b.Navigation("DangKyKems");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.HocVien", b =>
                {
                    b.Navigation("DangKyKems");

                    b.Navigation("DangKyLops");

                    b.Navigation("DangKySuKiens");

                    b.Navigation("KetQuaThis");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.HuanLuyenVien", b =>
                {
                    b.Navigation("DangKyKems");

                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.KhoaHoc", b =>
                {
                    b.Navigation("GoiKemRiengs");

                    b.Navigation("KyThiThangDais");

                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.KyThiThangDai", b =>
                {
                    b.Navigation("KetQuaThis");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.LopHoc", b =>
                {
                    b.Navigation("DangKyLops");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("HocVien");

                    b.Navigation("HuanLuyenVien");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("MartialArtsClubManagement.API.Models.Entities.ThongBao", b =>
                {
                    b.Navigation("DangKySuKiens");
                });
#pragma warning restore 612, 618
        }
    }
}
